### ISSUE TITLE
Re-write for modern Paper

### ISSUE THREAD

**Issue by NotThatRqd** [thekdub/MiniWorld#1]
Hi, hoping this will reach TheKDub. I'm working on a plugin called "MiniWorld2" which is based off MiniWorld's code and for 1.19.4 Paper. I wanted to make sure you're cool with me using the name and all. I'm listing you as one of the authors as all of the code is based off your original. Lmk what you think. Thx

**Comment by thekdub** [comment]
Sure yeah, just be sure to give reference to the original MiniWorld as well!

Glad to see there's someone taking an interest in it!

**Comment by thekdub** [comment]
Added mention of MiniWorld2 in commit [5533157](https://github.com/thekdub/MiniWorld/commit/5533157dcac89a7c39881251e79ca701c12ffbcf).
